# Generated by Django 4.2.7 on 2023-11-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-date_created']},
        ),
    ]
