# Generated by Django 4.2.7 on 2023-11-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0002_alter_blogs_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Post',
        ),
    ]
