# Generated by Django 4.2.7 on 2023-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0004_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.TextField()),
                ('date_cmt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
