# Generated by Django 4.2.7 on 2023-11-20 17:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cmt',
            field=tinymce.models.HTMLField(),
        ),
    ]
