# Generated by Django 4.2.7 on 2023-12-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0010_alter_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_cmt']},
        ),
    ]
