# Generated by Django 4.2.7 on 2024-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0011_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='Blog_post', to='Blog_Website.user'),
        ),
    ]
