# Generated by Django 4.2.7 on 2024-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Website', '0012_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paswords',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
